server:
  port: 9090
  servlet:
    context-path: /template/server

logging:
  config: classpath:logback-spring.xml

basic:
  cors:
    host: "*"
  filter:
    enable: false
    excludes: /api/basic/user/*
